#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEC.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Time_Management")]
	public partial class TimeManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActivity_Log(Activity_Log instance);
    partial void UpdateActivity_Log(Activity_Log instance);
    partial void DeleteActivity_Log(Activity_Log instance);
    #endregion
		
		public TimeManagementDataContext() : 
				base(global::BISEC.Properties.Settings.Default.TIMEDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TimeManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimeManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dropdown_Activity> Dropdown_Activities
		{
			get
			{
				return this.GetTable<Dropdown_Activity>();
			}
		}
		
		public System.Data.Linq.Table<Dropdown_Car> Dropdown_Cars
		{
			get
			{
				return this.GetTable<Dropdown_Car>();
			}
		}
		
		public System.Data.Linq.Table<Dropdown_ClientLocation> Dropdown_ClientLocations
		{
			get
			{
				return this.GetTable<Dropdown_ClientLocation>();
			}
		}
		
		public System.Data.Linq.Table<Activity_Log> Activity_Logs
		{
			get
			{
				return this.GetTable<Activity_Log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BISECDropdown_Activity")]
	public partial class Dropdown_Activity
	{
		
		private string _Code;
		
		private string _Description;
		
		public Dropdown_Activity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(4)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BISECDropdown_Car")]
	public partial class Dropdown_Car
	{
		
		private string _CAR_DESCRIPTION;
		
		private int _CAR_ID;
		
		public Dropdown_Car()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_DESCRIPTION", DbType="VarChar(100)")]
		public string CAR_DESCRIPTION
		{
			get
			{
				return this._CAR_DESCRIPTION;
			}
			set
			{
				if ((this._CAR_DESCRIPTION != value))
				{
					this._CAR_DESCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CAR_ID
		{
			get
			{
				return this._CAR_ID;
			}
			set
			{
				if ((this._CAR_ID != value))
				{
					this._CAR_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BISECDropdown_ClientLocation")]
	public partial class Dropdown_ClientLocation
	{
		
		private string _ClientDescript;
		
		private int _ClientLocationID;
		
		public Dropdown_ClientLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientDescript", DbType="NVarChar(130)")]
		public string ClientDescript
		{
			get
			{
				return this._ClientDescript;
			}
			set
			{
				if ((this._ClientDescript != value))
				{
					this._ClientDescript = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientLocationID", DbType="Int NOT NULL")]
		public int ClientLocationID
		{
			get
			{
				return this._ClientLocationID;
			}
			set
			{
				if ((this._ClientLocationID != value))
				{
					this._ClientLocationID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLOYEE_ACTIVITY_LOGS")]
	public partial class Activity_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _log_id;
		
		private string _activity_code;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _end_time;
		
		private System.Nullable<int> _location_id;
		
		private System.Nullable<int> _car_id;
		
		private string _comments_254;
		
		private System.Nullable<bool> _need_approval_sw;
		
		private System.Nullable<bool> _approved_sw;
		
		private int _employee_id;
		
		private System.DateTime _activity_date;
		
		private string _punch_io_yn;
		
		private System.Nullable<bool> _all_day_sw;
		
		private System.Nullable<short> _log_status;
		
		private System.Nullable<int> _LunchBreakMinutes;
		
		private string _OnsiteCoEmployees;
		
		private string _LocationName;
		
		private System.Nullable<int> _orig_location_id;
		
		private System.Nullable<System.DateTime> _dtCreation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onactivity_codeChanging(string value);
    partial void Onactivity_codeChanged();
    partial void Onstart_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onend_timeChanged();
    partial void Onlocation_idChanging(System.Nullable<int> value);
    partial void Onlocation_idChanged();
    partial void Oncar_idChanging(System.Nullable<int> value);
    partial void Oncar_idChanged();
    partial void Oncomments_254Changing(string value);
    partial void Oncomments_254Changed();
    partial void Onneed_approval_swChanging(System.Nullable<bool> value);
    partial void Onneed_approval_swChanged();
    partial void Onapproved_swChanging(System.Nullable<bool> value);
    partial void Onapproved_swChanged();
    partial void Onemployee_idChanging(int value);
    partial void Onemployee_idChanged();
    partial void Onactivity_dateChanging(System.DateTime value);
    partial void Onactivity_dateChanged();
    partial void Onpunch_io_ynChanging(string value);
    partial void Onpunch_io_ynChanged();
    partial void Onall_day_swChanging(System.Nullable<bool> value);
    partial void Onall_day_swChanged();
    partial void Onlog_statusChanging(System.Nullable<short> value);
    partial void Onlog_statusChanged();
    partial void OnLunchBreakMinutesChanging(System.Nullable<int> value);
    partial void OnLunchBreakMinutesChanged();
    partial void OnOnsiteCoEmployeesChanging(string value);
    partial void OnOnsiteCoEmployeesChanged();
    partial void OnLocationNameChanging(string value);
    partial void OnLocationNameChanged();
    partial void Onorig_location_idChanging(System.Nullable<int> value);
    partial void Onorig_location_idChanged();
    partial void OndtCreationChanging(System.Nullable<System.DateTime> value);
    partial void OndtCreationChanged();
    #endregion
		
		public Activity_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity_code", DbType="VarChar(4)")]
		public string activity_code
		{
			get
			{
				return this._activity_code;
			}
			set
			{
				if ((this._activity_code != value))
				{
					this.Onactivity_codeChanging(value);
					this.SendPropertyChanging();
					this._activity_code = value;
					this.SendPropertyChanged("activity_code");
					this.Onactivity_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_id", DbType="Int")]
		public System.Nullable<int> location_id
		{
			get
			{
				return this._location_id;
			}
			set
			{
				if ((this._location_id != value))
				{
					this.Onlocation_idChanging(value);
					this.SendPropertyChanging();
					this._location_id = value;
					this.SendPropertyChanged("location_id");
					this.Onlocation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_id", DbType="Int")]
		public System.Nullable<int> car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments_254", DbType="VarChar(254)")]
		public string comments_254
		{
			get
			{
				return this._comments_254;
			}
			set
			{
				if ((this._comments_254 != value))
				{
					this.Oncomments_254Changing(value);
					this.SendPropertyChanging();
					this._comments_254 = value;
					this.SendPropertyChanged("comments_254");
					this.Oncomments_254Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_need_approval_sw", DbType="Bit")]
		public System.Nullable<bool> need_approval_sw
		{
			get
			{
				return this._need_approval_sw;
			}
			set
			{
				if ((this._need_approval_sw != value))
				{
					this.Onneed_approval_swChanging(value);
					this.SendPropertyChanging();
					this._need_approval_sw = value;
					this.SendPropertyChanged("need_approval_sw");
					this.Onneed_approval_swChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approved_sw", DbType="Bit")]
		public System.Nullable<bool> approved_sw
		{
			get
			{
				return this._approved_sw;
			}
			set
			{
				if ((this._approved_sw != value))
				{
					this.Onapproved_swChanging(value);
					this.SendPropertyChanging();
					this._approved_sw = value;
					this.SendPropertyChanged("approved_sw");
					this.Onapproved_swChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", DbType="Int NOT NULL")]
		public int employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity_date", DbType="Date NOT NULL")]
		public System.DateTime activity_date
		{
			get
			{
				return this._activity_date;
			}
			set
			{
				if ((this._activity_date != value))
				{
					this.Onactivity_dateChanging(value);
					this.SendPropertyChanging();
					this._activity_date = value;
					this.SendPropertyChanged("activity_date");
					this.Onactivity_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punch_io_yn", DbType="VarChar(1)")]
		public string punch_io_yn
		{
			get
			{
				return this._punch_io_yn;
			}
			set
			{
				if ((this._punch_io_yn != value))
				{
					this.Onpunch_io_ynChanging(value);
					this.SendPropertyChanging();
					this._punch_io_yn = value;
					this.SendPropertyChanged("punch_io_yn");
					this.Onpunch_io_ynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_all_day_sw", DbType="Bit")]
		public System.Nullable<bool> all_day_sw
		{
			get
			{
				return this._all_day_sw;
			}
			set
			{
				if ((this._all_day_sw != value))
				{
					this.Onall_day_swChanging(value);
					this.SendPropertyChanging();
					this._all_day_sw = value;
					this.SendPropertyChanged("all_day_sw");
					this.Onall_day_swChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_status", DbType="SmallInt")]
		public System.Nullable<short> log_status
		{
			get
			{
				return this._log_status;
			}
			set
			{
				if ((this._log_status != value))
				{
					this.Onlog_statusChanging(value);
					this.SendPropertyChanging();
					this._log_status = value;
					this.SendPropertyChanged("log_status");
					this.Onlog_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LunchBreakMinutes", DbType="Int")]
		public System.Nullable<int> LunchBreakMinutes
		{
			get
			{
				return this._LunchBreakMinutes;
			}
			set
			{
				if ((this._LunchBreakMinutes != value))
				{
					this.OnLunchBreakMinutesChanging(value);
					this.SendPropertyChanging();
					this._LunchBreakMinutes = value;
					this.SendPropertyChanged("LunchBreakMinutes");
					this.OnLunchBreakMinutesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnsiteCoEmployees", DbType="VarChar(100)")]
		public string OnsiteCoEmployees
		{
			get
			{
				return this._OnsiteCoEmployees;
			}
			set
			{
				if ((this._OnsiteCoEmployees != value))
				{
					this.OnOnsiteCoEmployeesChanging(value);
					this.SendPropertyChanging();
					this._OnsiteCoEmployees = value;
					this.SendPropertyChanged("OnsiteCoEmployees");
					this.OnOnsiteCoEmployeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationName", DbType="VarChar(254)")]
		public string LocationName
		{
			get
			{
				return this._LocationName;
			}
			set
			{
				if ((this._LocationName != value))
				{
					this.OnLocationNameChanging(value);
					this.SendPropertyChanging();
					this._LocationName = value;
					this.SendPropertyChanged("LocationName");
					this.OnLocationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_location_id", DbType="Int")]
		public System.Nullable<int> orig_location_id
		{
			get
			{
				return this._orig_location_id;
			}
			set
			{
				if ((this._orig_location_id != value))
				{
					this.Onorig_location_idChanging(value);
					this.SendPropertyChanging();
					this._orig_location_id = value;
					this.SendPropertyChanged("orig_location_id");
					this.Onorig_location_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtCreation", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtCreation
		{
			get
			{
				return this._dtCreation;
			}
			set
			{
				if ((this._dtCreation != value))
				{
					this.OndtCreationChanging(value);
					this.SendPropertyChanging();
					this._dtCreation = value;
					this.SendPropertyChanged("dtCreation");
					this.OndtCreationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
