//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BISEC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\documentation\quality_documentation\A2LA_Required Documents.
        /// </summary>
        internal static string A2LA_DOCUMENT_PATH {
            get {
                return ResourceManager.GetString("A2LA_DOCUMENT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BISEC.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\disk 1\BIS Equipment Management\BISEMv2\BISEMv2.mdb.
        /// </summary>
        internal static string BISEM_FILE_PATH {
            get {
                return ResourceManager.GetString("BISEM_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\Cal Forms New.
        /// </summary>
        internal static string CALIBRATION_FORM_PATH {
            get {
                return ResourceManager.GetString("CALIBRATION_FORM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon emp_center {
            get {
                object obj = ResourceManager.GetObject("emp_center", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Documentation\Quality_Documentation\Human_Resources\Handbook.doc.
        /// </summary>
        internal static string EMP_HANDBOOK_FILE_PATH {
            get {
                return ResourceManager.GetString("EMP_HANDBOOK_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\BISSERVER\SERVER\disk 1\BIS Corrective Action\CorrectiveAction.mdb.
        /// </summary>
        internal static string FILE_PATH_CORRECTIVE_ACTION {
            get {
                return ResourceManager.GetString("FILE_PATH_CORRECTIVE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\BISSERVER\SERVER\Documentation\Quality_Documentation\Procedures\BIS Complete Procedures eBook.pdf.
        /// </summary>
        internal static string FILE_PATH_PROCEDURE_EBOOK {
            get {
                return ResourceManager.GetString("FILE_PATH_PROCEDURE_EBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\manuals.
        /// </summary>
        internal static string MANUAL_PATH {
            get {
                return ResourceManager.GetString("MANUAL_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Computer.
        /// </summary>
        internal static string MY_COMPUTER_STRING {
            get {
                return ResourceManager.GetString("MY_COMPUTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\disk 1\On_Siite_WorkSheets_List_.
        /// </summary>
        internal static string ONSITE_FOLDER_PATH {
            get {
                return ResourceManager.GetString("ONSITE_FOLDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Software\BISPurchasing\BISPurchasing.Prod.application.
        /// </summary>
        internal static string PO_APP_INSTALLATION_URL {
            get {
                return ResourceManager.GetString("PO_APP_INSTALLATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadview Instrumentation.
        /// </summary>
        internal static string PUBLISHER_NAME_BIS {
            get {
                return ResourceManager.GetString("PUBLISHER_NAME_BIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hewlett-Packard.
        /// </summary>
        internal static string PUBLISHER_NAME_HP {
            get {
                return ResourceManager.GetString("PUBLISHER_NAME_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Software\BISQC\BISQC.application.
        /// </summary>
        internal static string QC_APP_INSTALLATION_URL {
            get {
                return ResourceManager.GetString("QC_APP_INSTALLATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Software\BISQoSys\BISQT.Desktop.application.
        /// </summary>
        internal static string QT_APP_INSTALLATION_URL {
            get {
                return ResourceManager.GetString("QT_APP_INSTALLATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\documentation\quality_documentation\forms.
        /// </summary>
        internal static string QUALITY_FORM_PATH {
            get {
                return ResourceManager.GetString("QUALITY_FORM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Documentation\Quality_Documentation\Quality_Manual\Quality_Manual.pdf.
        /// </summary>
        internal static string QUALITY_MANUAL_FILE_PATH {
            get {
                return ResourceManager.GetString("QUALITY_MANUAL_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Documentation\Quality_Documentation\Human_Resources\Safety and Health Book_Rev1.10.doc.
        /// </summary>
        internal static string SAFETY_HANDBOOK_FILE_PATH {
            get {
                return ResourceManager.GetString("SAFETY_HANDBOOK_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\Server\Documentation\Quality_Documentation\Scope\scope.pdf.
        /// </summary>
        internal static string SCOPE_FILE_PATH {
            get {
                return ResourceManager.GetString("SCOPE_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server.
        /// </summary>
        internal static string SERVER_PATH {
            get {
                return ResourceManager.GetString("SERVER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string SUITE_NAME {
            get {
                return ResourceManager.GetString("SUITE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\BISSERVER\Server\Software\TrainingApp\Training.application.
        /// </summary>
        internal static string TRAINING_APP_INSTALLATION_URL {
            get {
                return ResourceManager.GetString("TRAINING_APP_INSTALLATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\disk 1\Work.
        /// </summary>
        internal static string WORK_FOLDER_DIR {
            get {
                return ResourceManager.GetString("WORK_FOLDER_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bisserver\server\History.
        /// </summary>
        internal static string WORK_HISTORY_DIR {
            get {
                return ResourceManager.GetString("WORK_HISTORY_DIR", resourceCulture);
            }
        }
    }
}
