//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"\\\\bisserver\\server\\disk 1\\DB Dataso" +
            "urce\\BISEMv2.mdb\"")]
        public string BISEMConnectrionString {
            get {
                return ((string)(this["BISEMConnectrionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000")]
        public string ADMIN_CODE {
            get {
                return ((string)(this["ADMIN_CODE"]));
            }
            set {
                this["ADMIN_CODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("To ensure that verification and calibration of test and measuring equipment is ca" +
            "rried out in a consistent, proper and unbiased manner.")]
        public string BIS_QUALITY_STATEMENT_1 {
            get {
                return ((string)(this["BIS_QUALITY_STATEMENT_1"]));
            }
            set {
                this["BIS_QUALITY_STATEMENT_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BIS is committed to satisfying customer requirements.")]
        public string BIS_QUALITY_STATEMENT_2 {
            get {
                return ((string)(this["BIS_QUALITY_STATEMENT_2"]));
            }
            set {
                this["BIS_QUALITY_STATEMENT_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NOTIFY_COMPLETE_EQUIPMENT_SW {
            get {
                return ((bool)(this["NOTIFY_COMPLETE_EQUIPMENT_SW"]));
            }
            set {
                this["NOTIFY_COMPLETE_EQUIPMENT_SW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NOTIFY_MISSING_PAYMENT_OPTION_SW {
            get {
                return ((bool)(this["NOTIFY_MISSING_PAYMENT_OPTION_SW"]));
            }
            set {
                this["NOTIFY_MISSING_PAYMENT_OPTION_SW"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VALLEYVIEW;Initial Catalog=EQMAN;Persist Security Info=True;User ID=a" +
            "ppuser;Password=123456bIs")]
        public string EQMANConnectionString {
            get {
                return ((string)(this["EQMANConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10001")]
        public int UserID {
            get {
                return ((int)(this["UserID"]));
            }
            set {
                this["UserID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BISSERVER;Initial Catalog=Time_Management;Persist Security Info=True;" +
            "User ID=dbuser;Password=123456bIs")]
        public string TIMEDBConnectionString {
            get {
                return ((string)(this["TIMEDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TIMESHEET_ADMIN_ROLE_ID {
            get {
                return ((int)(this["TIMESHEET_ADMIN_ROLE_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\osdoc\\")]
        public string ONSITE_LOCAL_PATH {
            get {
                return ((string)(this["ONSITE_LOCAL_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bisserver\\Server\\Software\\OnsiteData\\")]
        public string ONSITE_NETWORK_PATH {
            get {
                return ((string)(this["ONSITE_NETWORK_PATH"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NOTIFY_EQUIPMENT_QUEUE_SW {
            get {
                return ((bool)(this["NOTIFY_EQUIPMENT_QUEUE_SW"]));
            }
            set {
                this["NOTIFY_EQUIPMENT_QUEUE_SW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NOTIFY_OPEN_REPAIR_SW {
            get {
                return ((bool)(this["NOTIFY_OPEN_REPAIR_SW"]));
            }
            set {
                this["NOTIFY_OPEN_REPAIR_SW"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BISSERVER;Initial Catalog=admin;Persist Security Info=True;User ID=db" +
            "user;Password=123456bIs")]
        public string AdminDbConnectionString {
            get {
                return ((string)(this["AdminDbConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotShowNewReleaseSplashScreenAtStartup {
            get {
                return ((bool)(this["DoNotShowNewReleaseSplashScreenAtStartup"]));
            }
            set {
                this["DoNotShowNewReleaseSplashScreenAtStartup"] = value;
            }
        }
    }
}
